### ISSUE TITLE
Use this script with a wav file

### ISSUE THREAD

**Issue by Wylarel** [tr1pzz/Realtime_PyAudio_FFT#12]
Hello!

I would like to use this visualizer but with a WAV file as an input instead of a microphone stream. It should be pretty easy to edit the code to use a Wave_read object (from the wave package) instead of the current input, but I can't manage to do it. Perhaps someone here can help me?

Thanks for your wonderful job btw, this is a really good ressource :)

**Comment by Wylarel** [comment]
Nevermind, it got it to work.

**Comment by DiegoMartinezGlez** [comment]
Hi @Wylarel , do you mind to share your solution?
