### ISSUE TITLE
error installing on mint 19.3

### ISSUE THREAD

**Issue by andreampiovesana** [tr1pzz/Realtime_PyAudio_FFT#3]
i use virtualenv:
virtualenv -p /usr/bin/python3.6 venv-3.6
source venv-3.6/bin/activate
pip3 install -r requirements.txt

i changed the requirement file to include versions (i suggest to update the file with versions)
numpy==1.18.4
matplotlib==3.2.1
scipy==1.4.1
pygame==1.9.6
PyAudio==0.2.11

but pyAudio give me error
Collecting PyAudio==0.2.11
  src/_portaudiomodule.c:29:10: fatal error: portaudio.h: File o directory non esistente
   #include "portaudio.h"
            ^~~~~~~~~~~~~
  compilation terminated.

solved installing portaudio via apt:

sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0

**Comment by tr1pzz** [comment]
Done! Added those to the requirements.txt and README files, thx for the feedback
